"""Python within-session direction decoding for the PPC fUSI dataset."""

from .cross_session import (
    CrossSessionConfig,
    CrossSessionGroup,
    run_cross_session_decoding,
    run_cross_session_pair,
    run_loso_cross_session_group,
    run_pairwise_cross_session_group,
    summarize_cross_session_results,
)
from .within_session import (
    WithinSessionConfig,
    align_fusi_and_behavior,
    apply_bonferroni_correction,
    build_dynamic_window_features,
    build_fixed_memory_3frames_features,
    compute_angular_error,
    decode_within_session,
    infer_task_config,
    load_mat73_session,
    make_binary_labels,
    make_multicoder_labels,
    permutation_test_angular_error,
    plot_within_session_results,
    preprocess_power_doppler_session,
)

__all__ = [
    "CrossSessionConfig",
    "CrossSessionGroup",
    "WithinSessionConfig",
    "align_fusi_and_behavior",
    "apply_bonferroni_correction",
    "build_dynamic_window_features",
    "build_fixed_memory_3frames_features",
    "compute_angular_error",
    "decode_within_session",
    "infer_task_config",
    "load_mat73_session",
    "make_binary_labels",
    "make_multicoder_labels",
    "permutation_test_angular_error",
    "plot_within_session_results",
    "preprocess_power_doppler_session",
    "run_cross_session_decoding",
    "run_cross_session_pair",
    "run_loso_cross_session_group",
    "run_pairwise_cross_session_group",
    "summarize_cross_session_results",
]
